version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  commit-message:
    prefix: ":arrow_upper_right: [patch]"
    include: "scope"
