group: edge
language: go
sudo: required

go_import_path: github.com/ahmedkamals/eventually

git:
  depth: 8

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

env:
  global:
    - secure: "ArGVSyf+Wk9qZtfKzpkCaBSM8wassLRdlBWQb8Cmda8DOIISEko6n9X4YOE5VTeDY2eJizVbVEbDQjm0/EtMNyuxfWBrVg1wyDCASXdmrVDMPxp4Ptu2CZMd3O7gEgjGgiPTES+gHQ3O4Jwu6fVjIBFUWVkls4RnAxyc9K3KY9TvjPJRH1RGLMAY7mjH/7HPYLNjxAHfaoQNVPeIY7COw8AR8CTD2lp9FXEzsl1C4RA33Xv8ZHZnU8DpDuPVx2xTuQtaCChJRN2g8uMr1X+mDR3P91svi7D1698E+4Txtozhw690DaAElRljAhMyVPv/j5vTZujNPNG3zRh6SssFWR9rpYkHrd5ZD2JZvBzd6CA5UfTm4Ch86ipZgoOrPVWAazQF4nbdf2MKG9R3t9whHkgdMEIuZpcrlVdlxuhhmFMjvcL/6yotOSZK3+/gPCHjweMRgvO6NYCaOnGVDK9u7Uc9a0eup45oh07EePiEyDk+rva41rGYYuJRl09zQTar4XN3c5pRz9UxaRQQ3qN2AZ8KXOVfT9Cly1QddI/uIvXVApopooYBzTA56ZGWo8lQ0jN4aGUpRMjHsbE3wGXRiIaWvpnKEnRLNce7VyLysuzRkvpVzKwsPqoQJoBL3ELjPkc4dWVU+OfDfXqKxpjlpTjgsMYoIzMtpwL+94HT7L8="
    - BUILD=false
    - GO111MODULE=on

branches:
  only:
    # Pushes and PR to the master branch
    - master
    - stable
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - stage: Coverage
      go: 1.16
      env: COVERAGE=true
      install:
        - make get-deps
    - &integration-tests
      stage: Integration tests
      go: 1.16.x
      os: linux
      env:
        - Build=true
        - INTEGRATION=true
    - <<: *integration-tests
      os: osx
    - <<: *integration-tests
      go: tip
    - <<: *integration-tests
      go: tip
      os: osx

before_install:
  - bash ./.travis/install.sh

install:
  - make go-install

script:
  # This to fix the error "fatal: ref HEAD is not a symbolic ref", that appears after every make call.
  - git checkout -b build-${TRAVIS_PULL_REQUEST}
  - if [ "$BUILD" == true ]; then make build; else echo 'skipping build.'; fi
  - if [ "$COVERAGE" == true ]; then make cover; travis_retry make coverage-send || true; else echo 'skipping coverage.'; fi
  - if [ "$INTEGRATION" == true ]; then make integration; else echo 'skipping integratoin tests.'; fi

after_success:
  - make nuke
  - echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
  - echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}"
  - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"

notifications:
  email:
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f238c42f4cb872717a9b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
